language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install mongo-orchestration==0.3.1

before_script:
  - q -p 9088 > /dev/null 2>&1 &
  - mongo-orchestration start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
